services:
  - type: web
    name: myclassroom-api
    env: java
    buildCommand: ./gradlew installDist --no-daemon
    startCommand: ./build/install/MyClassRoom/bin/MyClassRoom
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myclassroom-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: myclassroom-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: myclassroom-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_DOMAIN
        value: https://myclassroom.onrender.com/
      - key: JWT_AUDIENCE
        value: jwt-audience
      - key: JWT_REALM
        value: ktor sample app

databases:
  - name: myclassroom-db
    databaseName: classloom
    user: classloom_user
